-- ==================================================================
-- TABLES - MySQL
-- ==================================================================

-- SYS_USER
-- DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE IF NOT EXISTS `SYS_USER` (
	ID							BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CREATE_USER					VARCHAR(50) NOT NULL,
	CREATE_TIME					DATETIME NOT NULL,
	MODIFY_USER					VARCHAR(50) NOT NULL,
	MODIFY_TIME					DATETIME NOT NULL,
	
	SYS_STATUS					VARCHAR(1) NOT NULL,
	USERNAME					VARCHAR(50) NOT NULL,
	FIRSTNAME					VARCHAR(25),
	LASTNAME					VARCHAR(25),
	EMAIL						VARCHAR(100),
	DESCRIPTION					VARCHAR(500),
	PASSWORD					VARCHAR(100) NOT NULL,
	EXPIRE_TIME					DATETIME
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- SYS_ROLE
-- DROP TABLE IF EXISTS `SYS_ROLE`;
CREATE TABLE IF NOT EXISTS `SYS_ROLE` (
	ID							BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CREATE_USER					VARCHAR(50) NOT NULL,
	CREATE_TIME					DATETIME NOT NULL,
	MODIFY_USER					VARCHAR(50) NOT NULL,
	MODIFY_TIME					DATETIME NOT NULL,
	
	SYS_STATUS					VARCHAR(1) NOT NULL,
	CODE						VARCHAR(50) NOT NULL,
	NAME						VARCHAR(100) NOT NULL,
	DESCRIPTION					TEXT
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- SYS_USER_ROLE
-- DROP TABLE IF EXISTS `SYS_USER_ROLE`;
CREATE TABLE IF NOT EXISTS `SYS_USER_ROLE` (
	ID							BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	
	USER_ID						BIGINT NOT NULL,
	ROLE_ID						BIGINT NOT NULL
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;
